language: go
go:
  - master
os:
  - linux
  - osx
dist: trusty
sudo: false
install: true
script:
  - env GO111MODULE=on go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - env GO111MODULE=on go build cmd/jarvis/*.go

after_success:
  - bash <(curl -s https://codecov.io/bash)