global:
  trans: "translation"
  lang: "en"
  httpaddr: ":9005"
cluster:
  # see detail of custom cluster here:
  type: "custom"
  kubeconfig: ""

diagnostics:
  - type: "master-capacity"
  - type: "master-components"
  - type: "node-sys"
  - type: "requests-limits"

exporters:
  - type: "file"
    name: "for json"
    config:
    format: "json"
    path: "result.json"

