global:
  trans: "translation"
  lang: "en"
  cluster:
    kubeconfig: "fake"
coordinator:
  type: "default"

diagnostics:
  - type: "example"
    name: "example 1"
    score: 10
    weight: 10
    config:
      message: "message"

evaluators:
  - type: "sum"
    name: "sum 1"

exporters:
  - type: "stdout"
    name: "stdout 1"
