global:
  trans: "translation"
  lang: "en"
  cloud: "qcloud"
  cluster:
    kubeconfig: "fake"

coordinator:
  type: "default"

diagnostics:
  - type: "example"
    name: "example 1"
    score: 100
    config:
      message: "message"

  - type: "requests-limits"
    name: "pod requests-limits"
    score: 100

evaluators:
  - type: "sum"
    name: "sum 1"

exporters:
  - type: "stdout"
    name: "stdout 1"
