global:
  trans: "translation"
  lang: "en"
  cloud: "qcloud"
  cluster:
    kubeconfig: ""

coordinator:
  type: "default"

diagnostics:
  # items for master
  - type: "master-capacity"
  # items for resources
  - type: "requests-limits"


evaluators:
  - type: "sum"

exporters:
  - type: "stdout"
