global:
  trans: "translation"
  lang: "en"
  httpaddr: ":9005"
cluster:
  # see detail of custom cluster here:
  type: "custom"
  kubeconfig: ""
  config:
    node:
      autocreate: true

diagnostics:
  - type: "master-capacity"
  - type: "master-components"
  - type: "node-sys"
  - type: "node-iptables"
  - type: "node-status"
  - type: "workload-status"
  - type: "requests-limits"
  - type: "health-check"
  - type: "affinity"
  - type: "pdb"
  - type: "batch-check"
  - type: "hpa-ip"
  - type: "node-ha"

exporters:
  - type: "stdout"

