apiVersion: v1
data:
  default.yaml: |
    global:
      trans: "translation"
      lang: "en"

    cluster:
      # see detail of custom cluster here:
      type: "custom"
      kubeconfig: ""

    diagnostics:
      - type: "master-capacity"
      - type: "master-apiserver"
      - type: "node-sys"
      - type: "requests-limits"

    exporters:
      - type: "stdout"

      - type: "file"
        name: "for json"
        config:
          format: "json"
          path: "result.json"

kind: ConfigMap
metadata:
  name: config
  namespace: kube-jarvis